import type {
  Folder,
  File,
  Question,
  Project,
  User,
  TrackerItem,
  CategorySuggestion,
  Permission,
  QATrackingItem,
} from "./store"

// Mock folder structure as specified in requirements
export const mockFolders: Folder[] = [
  { id: "legal", name: "Legal", path: "/Legal", visibleTo: "All" },
  {
    id: "legal-corp",
    name: "Corporate Organization",
    path: "/Legal/Corporate Organization",
    parentId: "legal",
    visibleTo: "All",
  },
  { id: "legal-mgmt", name: "Management", path: "/Legal/Management", parentId: "legal", visibleTo: "All" },
  {
    id: "legal-capital",
    name: "Capital Structure",
    path: "/Legal/Capital Structure",
    parentId: "legal",
    visibleTo: "All",
  },
  { id: "legal-legal", name: "Legal", path: "/Legal/Legal", parentId: "legal", visibleTo: "All" },
  { id: "legal-realestate", name: "Real Estate", path: "/Legal/Real Estate", parentId: "legal", visibleTo: "All" },

  { id: "commercial", name: "Commercial", path: "/Commercial", visibleTo: "All" },
  {
    id: "commercial-customers",
    name: "Customers",
    path: "/Commercial/Customers",
    parentId: "commercial",
    visibleTo: "All",
  },
  {
    id: "commercial-it",
    name: "IT Administration",
    path: "/Commercial/IT Administration",
    parentId: "commercial",
    visibleTo: "All",
  },
  {
    id: "commercial-contracts",
    name: "Contracts",
    path: "/Commercial/Customers/Contracts",
    parentId: "commercial-customers",
    visibleTo: "All",
  },
  {
    id: "commercial-policies",
    name: "Commercial Policies",
    path: "/Commercial/Commercial Policies",
    parentId: "commercial",
    visibleTo: "All",
  },
  {
    id: "commercial-marketing",
    name: "Marketing",
    path: "/Commercial/Marketing",
    parentId: "commercial",
    visibleTo: "All",
  },
  {
    id: "commercial-suppliers",
    name: "Suppliers",
    path: "/Commercial/Suppliers",
    parentId: "commercial",
    visibleTo: "All",
  },
  {
    id: "commercial-supplier-contacts",
    name: "Contacts",
    path: "/Commercial/Suppliers/Contacts",
    parentId: "commercial-suppliers",
    visibleTo: "All",
  },

  { id: "financial", name: "Financial", path: "/Financial", visibleTo: "All" },
  {
    id: "financial-accounting",
    name: "Accounting",
    path: "/Financial/Accounting",
    parentId: "financial",
    visibleTo: "All",
  },
  { id: "financial-finance", name: "Finance", path: "/Financial/Finance", parentId: "financial", visibleTo: "All" },
  {
    id: "financial-operations",
    name: "Operations",
    path: "/Financial/Operations",
    parentId: "financial",
    visibleTo: "All",
  },
  {
    id: "financial-insurance",
    name: "Insurance",
    path: "/Financial/Insurance",
    parentId: "financial",
    visibleTo: "All",
  },

  { id: "hr", name: "HR", path: "/HR", visibleTo: "All" },
  { id: "hr-agreements", name: "HR Agreements", path: "/HR/HR Agreements", parentId: "hr", visibleTo: "All" },
  { id: "hr-benefits", name: "Benefits", path: "/HR/Benefits", parentId: "hr", visibleTo: "All" },
  { id: "hr-general", name: "General HR", path: "/HR/General HR", parentId: "hr", visibleTo: "All" },
  { id: "hr-policies", name: "HR Policies", path: "/HR/HR Policies", parentId: "hr", visibleTo: "All" },

  { id: "ip", name: "IP", path: "/IP", visibleTo: "All" },
  { id: "ip-registrations", name: "IP Registrations", path: "/IP/IP Registrations", parentId: "ip", visibleTo: "All" },
  { id: "ip-contracts", name: "IP Contracts", path: "/IP/IP Contracts", parentId: "ip", visibleTo: "All" },
  { id: "ip-litigation", name: "IP Litigation", path: "/IP/IP Litigation", parentId: "ip", visibleTo: "All" },
  { id: "ip-development", name: "IP Development", path: "/IP/IP Development", parentId: "ip", visibleTo: "All" },

  { id: "it", name: "IT", path: "/IT", visibleTo: "All" },
  {
    id: "it-administration",
    name: "IT Administration",
    path: "/IT/IT Administration",
    parentId: "it",
    visibleTo: "All",
  },
  { id: "it-security", name: "IT Security", path: "/IT/IT Security", parentId: "it", visibleTo: "All" },
]

export const mockFiles: File[] = [
  {
    id: "file-1",
    name: "Articles of Incorporation.pdf",
    path: "/Legal/Corporate Organization/Articles of Incorporation.pdf",
    folderId: "legal-corp",
    size: 2456789,
    modified: "2024-01-15T10:30:00Z",
    version: "1.0",
    visibleTo: "All",
    type: "pdf",
    uploadedBy: "Legal Team",
  },
  {
    id: "file-2",
    name: "Board Resolutions 2023.pdf",
    path: "/Legal/Management/Board Resolutions 2023.pdf",
    folderId: "legal-mgmt",
    size: 1234567,
    modified: "2024-01-14T15:45:00Z",
    version: "2.1",
    visibleTo: ["Buyer A"],
    type: "pdf",
    uploadedBy: "Legal Team",
  },
  {
    id: "file-3",
    name: "Customer Contracts Summary.xlsx",
    path: "/Commercial/Customers/Customer Contracts Summary.xlsx",
    folderId: "commercial-customers",
    size: 987654,
    modified: "2024-01-16T09:15:00Z",
    version: "1.3",
    visibleTo: "All",
    type: "xlsx",
    uploadedBy: "Commercial Team",
  },
  {
    id: "file-4",
    name: "Financial Statements Q4 2023.pdf",
    path: "/Financial/Accounting/Financial Statements Q4 2023.pdf",
    folderId: "financial-accounting",
    size: 3456789,
    modified: "2024-01-12T14:20:00Z",
    version: "1.0",
    visibleTo: ["Buyer A", "Buyer B"],
    type: "pdf",
    uploadedBy: "Finance Team",
  },
]

export const mockQuestions: Question[] = [
  {
    id: "q-1",
    buyerId: "buyer-a",
    priority: "High",
    status: "Open",
    requestedItem: "Corporate governance documents",
    dueDate: "2024-01-25",
    reviewedByBank: "Not Started",
    category: "Legal",
    subcategory: "Corporate Organization",
    description:
      "Please provide all corporate governance documents including board resolutions, bylaws, and organizational charts.",
    team: "Legal",
    linkedFiles: ["file-1"],
  },
  {
    id: "q-2",
    buyerId: "buyer-b",
    priority: "Medium",
    status: "In Progress",
    requestedItem: "Customer contract details",
    dueDate: "2024-01-28",
    reviewedByBank: "In Progress",
    category: "Commercial",
    subcategory: "Customers",
    description: "Detailed breakdown of top 10 customer contracts including terms, renewal dates, and revenue impact.",
    team: "Commercial",
    linkedFiles: ["file-3"],
  },
  {
    id: "q-3",
    buyerId: "buyer-a",
    priority: "High",
    status: "Answered",
    requestedItem: "Latest financial statements",
    dueDate: "2024-01-20",
    reviewedByBank: "Yes",
    category: "Financial",
    subcategory: "Accounting",
    description: "Most recent audited financial statements and management accounts.",
    team: "Finance",
    linkedFiles: ["file-4"],
  },
]

export const mockProjects: Project[] = [
  {
    id: "project-pearl",
    name: "Project Pearl",
    description: "Strategic acquisition of manufacturing assets",
    buyers: ["Buyer A", "Buyer B"],
    qaCompletionPct: 78,
    lastActivity: "2 hours ago",
    status: "Active",
    dueDate: "2024-02-15",
  },
  {
    id: "project-diamond",
    name: "Project Diamond",
    description: "Technology company merger and integration",
    buyers: ["Buyer A"],
    qaCompletionPct: 92,
    lastActivity: "1 day ago",
    status: "Due Diligence",
    dueDate: "2024-01-30",
  },
]

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "John Doe",
    email: "john.doe@bank.com",
    role: "Seller Admin",
    avatar: "JD",
    access: { view: true, upload: true, qa: true, respond: true },
    folderPermissions: ["legal", "commercial", "financial", "hr", "ip", "it"],
  },
  {
    id: "user-2",
    name: "Jane Smith",
    email: "jane.smith@company.com",
    role: "Company Legal",
    avatar: "JS",
    access: { view: true, upload: true, qa: false, respond: true },
    folderPermissions: ["legal", "ip"],
  },
  {
    id: "user-3",
    name: "Mike Johnson",
    email: "mike.johnson@company.com",
    role: "Company Finance",
    avatar: "MJ",
    access: { view: true, upload: true, qa: false, respond: true },
    folderPermissions: ["financial"],
  },
  {
    id: "user-4",
    name: "Sarah Wilson",
    email: "sarah.wilson@buyera.com",
    role: "Buyer A",
    avatar: "SW",
    access: { view: true, upload: false, qa: true, respond: false },
    folderPermissions: ["legal", "commercial", "financial"],
    buyerGroup: "Buyer A",
  },
  {
    id: "user-5",
    name: "David Brown",
    email: "david.brown@buyerb.com",
    role: "Buyer B",
    avatar: "DB",
    access: { view: true, upload: false, qa: true, respond: false },
    folderPermissions: ["commercial", "financial", "hr"],
    buyerGroup: "Buyer B",
  },
  {
    id: "user-6",
    name: "Lisa Chen",
    email: "lisa.chen@company.com",
    role: "Seller Analyst",
    avatar: "LC",
    access: { view: true, upload: false, qa: false, respond: false },
    folderPermissions: ["commercial", "financial"],
  },
]

export const mockTrackerItems: TrackerItem[] = [
  {
    id: "tracker-1",
    indexLink: "Corporate Documents",
    folderPath: "/Legal/Corporate Organization",
    status: "Complete",
    team: "Legal",
    requestedItem: "Articles of Incorporation and Bylaws",
    reviewedByBank: "Yes",
    dueDate: "2024-01-20",
    priority: "High",
    questionId: "q-1",
    description:
      "Provide complete corporate governance documentation including articles of incorporation, bylaws, and board resolutions.",
    history: [
      { date: "2024-01-15", action: "Uploaded", user: "Legal Team", note: "Initial documents uploaded" },
      { date: "2024-01-18", action: "Reviewed", user: "Bank Reviewer", note: "Documents approved" },
    ],
  },
  {
    id: "tracker-2",
    indexLink: "Financial Statements",
    folderPath: "/Financial/Accounting",
    status: "In Progress",
    team: "Finance",
    requestedItem: "Audited Financial Statements (3 years)",
    reviewedByBank: "In Progress",
    dueDate: "2024-01-25",
    priority: "High",
    questionId: "q-3",
    description:
      "Three years of audited financial statements including balance sheet, income statement, and cash flow.",
    history: [
      { date: "2024-01-12", action: "Requested", user: "Buyer A", note: "Initial request submitted" },
      { date: "2024-01-16", action: "Partial Upload", user: "Finance Team", note: "2023 statements uploaded" },
    ],
  },
  {
    id: "tracker-3",
    indexLink: "Customer Contracts",
    folderPath: "/Commercial/Customers",
    status: "Open",
    team: "Commercial",
    requestedItem: "Top 10 Customer Agreements",
    reviewedByBank: "Not Started",
    dueDate: "2024-01-28",
    priority: "Medium",
    questionId: "q-2",
    description: "Contracts for the top 10 customers by revenue including terms, renewal dates, and pricing.",
    history: [{ date: "2024-01-14", action: "Assigned", user: "Deal Manager", note: "Assigned to commercial team" }],
  },
  {
    id: "tracker-4",
    indexLink: "IP Portfolio",
    folderPath: "/IP/IP Registrations",
    status: "Open",
    team: "Legal",
    requestedItem: "Patent and Trademark Registrations",
    reviewedByBank: "Not Started",
    dueDate: "2024-02-01",
    priority: "Low",
    description: "Complete intellectual property portfolio including patents, trademarks, and copyrights.",
    history: [{ date: "2024-01-10", action: "Created", user: "System", note: "Tracker item created" }],
  },
  {
    id: "tracker-5",
    indexLink: "HR Policies",
    folderPath: "/HR/HR Policies",
    status: "In Progress",
    team: "HR",
    requestedItem: "Employee Handbook and Policies",
    reviewedByBank: "In Progress",
    dueDate: "2024-01-30",
    priority: "Medium",
    description: "Current employee handbook, HR policies, and organizational structure.",
    history: [{ date: "2024-01-13", action: "Started", user: "HR Team", note: "Document compilation started" }],
  },
]

export const mockCategorySuggestions: CategorySuggestion[] = [
  {
    questionId: "q-1",
    suggestion: {
      category: "Legal",
      subcategory: "Corporate Organization",
      confidence: 0.92,
      alternatives: ["Legal/Management", "Legal/Capital Structure"],
    },
  },
  {
    questionId: "q-2",
    suggestion: {
      category: "Commercial",
      subcategory: "Customers",
      confidence: 0.88,
      alternatives: ["Commercial/Marketing", "Financial/Operations"],
    },
  },
  {
    questionId: "q-3",
    suggestion: {
      category: "Financial",
      subcategory: "Accounting",
      confidence: 0.95,
      alternatives: ["Financial/Finance", "Financial/Operations"],
    },
  },
]

export const mockPermissions: Permission[] = [
  { userId: "user-1", folderId: "legal", canView: true, canUpload: true, canModify: true },
  { userId: "user-1", folderId: "commercial", canView: true, canUpload: true, canModify: true },
  { userId: "user-2", folderId: "legal", canView: true, canUpload: true, canModify: false },
  { userId: "user-3", folderId: "financial", canView: true, canUpload: true, canModify: false },
  { userId: "user-4", folderId: "legal", canView: true, canUpload: false, canModify: false },
  { userId: "user-5", folderId: "commercial", canView: true, canUpload: false, canModify: false },
]

export const mockAnalyticsData = {
  topViewedFolders: [
    { name: "Financial Statements", path: "/Financial/Accounting", views: 156, trend: "+12%" },
    { name: "Corporate Documents", path: "/Legal/Corporate Organization", views: 134, trend: "+8%" },
    { name: "Customer Contracts", path: "/Commercial/Customers", views: 98, trend: "+15%" },
    { name: "IP Registrations", path: "/IP/IP Registrations", views: 67, trend: "-3%" },
    { name: "HR Policies", path: "/HR/HR Policies", views: 45, trend: "+5%" },
  ],
  recentActivity: [
    {
      id: "1",
      type: "upload",
      user: "Legal Team",
      action: "uploaded",
      item: "Board Resolution 2024.pdf",
      folder: "/Legal/Management",
      timestamp: "2024-01-16T14:30:00Z",
    },
    {
      id: "2",
      type: "question",
      user: "Buyer A",
      action: "submitted question about",
      item: "Tax compliance documents",
      folder: "/Financial/Tax",
      timestamp: "2024-01-16T13:45:00Z",
    },
    {
      id: "3",
      type: "review",
      user: "Bank Reviewer",
      action: "approved",
      item: "Financial Statements Q4 2023.pdf",
      folder: "/Financial/Accounting",
      timestamp: "2024-01-16T12:15:00Z",
    },
    {
      id: "4",
      type: "access",
      user: "Jane Smith",
      action: "granted access to",
      item: "IP Development folder",
      folder: "/IP/IP Development",
      timestamp: "2024-01-16T11:20:00Z",
    },
    {
      id: "5",
      type: "upload",
      user: "Finance Team",
      action: "uploaded",
      item: "Cash Flow Analysis.xlsx",
      folder: "/Financial/Finance",
      timestamp: "2024-01-16T10:45:00Z",
    },
  ],
  qaThroughput: {
    totalQuestions: 47,
    answeredQuestions: 32,
    pendingQuestions: 15,
    averageResponseTime: "2.3 days",
    weeklyData: [
      { day: "Mon", submitted: 8, answered: 6 },
      { day: "Tue", submitted: 12, answered: 9 },
      { day: "Wed", submitted: 6, answered: 11 },
      { day: "Thu", submitted: 9, answered: 7 },
      { day: "Fri", submitted: 7, answered: 8 },
      { day: "Sat", submitted: 3, answered: 2 },
      { day: "Sun", submitted: 2, answered: 1 },
    ],
  },
  documentStats: {
    totalDocuments: 234,
    documentsThisWeek: 18,
    totalSize: "2.4 GB",
    averageFileSize: "10.5 MB",
  },
  userActivity: {
    activeUsers: 12,
    totalLogins: 89,
    peakHours: "2:00 PM - 4:00 PM",
    mostActiveUser: "John Doe",
  },
}

export const mockQATrackingItems: QATrackingItem[] = [
  {
    id: "qa-1",
    question: "What are the company's main revenue streams and how have they performed over the last 3 years?",
    buyerId: "buyer-a",
    status: "Complete",
    team: "Finance",
    category: "Financial",
    subcategory: "Revenue Analysis",
    priority: "High",
    dueDate: "2024-01-20",
    reviewedByBank: "Yes",
    description: "Detailed breakdown of revenue streams including growth trends, seasonality, and key drivers.",
    linkedFiles: ["file-4"], // Links to Financial Statements Q4 2023.pdf
    submittedDate: "2024-01-10",
    history: [
      { date: "2024-01-10", action: "Submitted", user: "Buyer A", note: "Initial question submitted" },
      { date: "2024-01-15", action: "Assigned", user: "Deal Manager", note: "Assigned to Finance team" },
      { date: "2024-01-18", action: "Answered", user: "Finance Team", note: "Complete response provided" },
      { date: "2024-01-20", action: "Approved", user: "Bank Reviewer", note: "Response approved" },
    ],
  },
  {
    id: "qa-2",
    question: "Can you provide details on any pending litigation or regulatory investigations?",
    buyerId: "buyer-b",
    status: "In Progress",
    team: "Legal",
    category: "Legal",
    subcategory: "Litigation",
    priority: "High",
    dueDate: "2024-01-25",
    reviewedByBank: "In Progress",
    description:
      "Comprehensive overview of all legal matters including timeline, potential exposure, and mitigation strategies.",
    linkedFiles: [],
    submittedDate: "2024-01-12",
    history: [
      { date: "2024-01-12", action: "Submitted", user: "Buyer B", note: "Question about legal matters" },
      { date: "2024-01-14", action: "Assigned", user: "Deal Manager", note: "Assigned to Legal team" },
      { date: "2024-01-16", action: "In Review", user: "Legal Team", note: "Gathering information" },
    ],
  },
  {
    id: "qa-3",
    question: "What is the company's customer concentration risk and retention rates?",
    buyerId: "buyer-a",
    status: "Complete", // Changed from Open to Complete to show source link
    team: "Commercial",
    category: "Commercial",
    subcategory: "Customer Analysis",
    priority: "Medium",
    dueDate: "2024-01-28",
    reviewedByBank: "Yes", // Changed from Not Started to Yes
    description: "Analysis of top customer relationships, contract terms, and historical retention metrics.",
    linkedFiles: ["file-3"], // Links to Customer Contracts Summary.xlsx
    submittedDate: "2024-01-14",
    history: [
      { date: "2024-01-14", action: "Submitted", user: "Buyer A", note: "Customer analysis request" },
      { date: "2024-01-16", action: "Assigned", user: "Deal Manager", note: "Assigned to Commercial team" },
      { date: "2024-01-20", action: "Answered", user: "Commercial Team", note: "Complete analysis provided" },
      { date: "2024-01-22", action: "Approved", user: "Bank Reviewer", note: "Response approved" },
    ],
  },
  {
    id: "qa-4",
    question: "How does the company's intellectual property portfolio protect its competitive advantages?",
    buyerId: "buyer-b",
    status: "Open",
    team: "Legal",
    category: "IP",
    subcategory: "Patent Portfolio",
    priority: "Medium",
    dueDate: "2024-02-01",
    reviewedByBank: "Not Started",
    description: "Detailed review of patents, trademarks, trade secrets, and IP strategy.",
    linkedFiles: [],
    submittedDate: "2024-01-15",
    history: [{ date: "2024-01-15", action: "Submitted", user: "Buyer B", note: "IP portfolio inquiry" }],
  },
  {
    id: "qa-5",
    question: "What are the key employee retention risks and compensation structures?",
    buyerId: "buyer-a",
    status: "In Progress",
    team: "HR",
    category: "HR",
    subcategory: "Compensation",
    priority: "Low",
    dueDate: "2024-01-30",
    reviewedByBank: "In Progress",
    description: "Overview of key personnel, retention programs, and compensation benchmarking.",
    linkedFiles: [],
    submittedDate: "2024-01-13",
    history: [
      { date: "2024-01-13", action: "Submitted", user: "Buyer A", note: "HR and compensation inquiry" },
      { date: "2024-01-16", action: "Assigned", user: "Deal Manager", note: "Assigned to HR team" },
    ],
  },
  {
    id: "qa-6",
    question: "Can you explain the company's IT infrastructure and cybersecurity posture?",
    buyerId: "buyer-b",
    status: "Open",
    team: "IT",
    category: "IT",
    subcategory: "Security",
    priority: "High",
    dueDate: "2024-01-27",
    reviewedByBank: "Not Started",
    description: "Assessment of technology stack, security controls, and IT governance framework.",
    linkedFiles: [],
    submittedDate: "2024-01-16",
    history: [{ date: "2024-01-16", action: "Submitted", user: "Buyer B", note: "IT security assessment request" }],
  },
  {
    id: "qa-7",
    question: "What are the company's corporate governance structures and board composition?",
    buyerId: "buyer-a",
    status: "Complete",
    team: "Legal",
    category: "Legal",
    subcategory: "Corporate Organization",
    priority: "High",
    dueDate: "2024-01-18",
    reviewedByBank: "Yes",
    description: "Details on board structure, governance policies, and organizational hierarchy.",
    linkedFiles: ["file-1", "file-2"], // Links to Articles of Incorporation and Board Resolutions
    submittedDate: "2024-01-08",
    history: [
      { date: "2024-01-08", action: "Submitted", user: "Buyer A", note: "Corporate governance inquiry" },
      { date: "2024-01-10", action: "Assigned", user: "Deal Manager", note: "Assigned to Legal team" },
      { date: "2024-01-15", action: "Answered", user: "Legal Team", note: "Complete documentation provided" },
      { date: "2024-01-18", action: "Approved", user: "Bank Reviewer", note: "Response approved" },
    ],
  },
]
